'use client'
import { useSettings } from '@/lib/settings-context'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

export default function SettingsPage() {
  const { theme, accent, cardSize, setTheme, setAccent, setCardSize } = useSettings()

    const accentOptions: { key: 'blue' | 'purple' | 'green' | 'rose'; label: string; color: string }[] = [
        { key: 'blue', label: 'Biru', color: '#2563eb' },
            { key: 'purple', label: 'Ungu', color: '#9333ea' },
                { key: 'green', label: 'Hijau', color: '#059669' },
                    { key: 'rose', label: 'Merah Muda', color: '#e11d48' },
                      ]

                        return (
                            <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-6">
                                  <div className="max-w-2xl mx-auto">
                                          <h1 className="text-3xl font-bold text-slate-800 dark:text-slate-100 mb-2">Pengaturan</h1>
                                                  <p className="text-slate-500 dark:text-slate-400 mb-8">Sesuaikan tampilan sesuai preferensi kamu</p>

                                                          <div className="space-y-6">
                                                                    <Card className="card-modern border-0">
                                                                                <CardHeader><CardTitle className="text-slate-700 dark:text-slate-200 text-lg">Tema Tampilan</CardTitle></CardHeader>
                                                                                            <CardContent>
                                                                                                          <div className="grid grid-cols-2 gap-3">
                                                                                                                          {(['light', 'dark'] as const).map(t => (
                                                                                                                                            <button key={t} onClick={() => setTheme(t)}
                                                                                                                                                                className={`p-4 rounded-xl border-2 transition-all text-sm font-medium ${
                                                                                                                                                                                      theme === t ? 'accent-border accent-text' : 'border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400'
                                                                                                                                                                                                          }`}>
                                                                                                                                                                                                                              {t === 'light' ? 'Terang' : 'Gelap'}
                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                          </CardContent>
                                                                                                                                                                                                                                                                                                    </Card>

                                                                                                                                                                                                                                                                                                              <Card className="card-modern border-0">
                                                                                                                                                                                                                                                                                                                          <CardHeader><CardTitle className="text-slate-700 dark:text-slate-200 text-lg">Warna Aksen</CardTitle></CardHeader>
                                                                                                                                                                                                                                                                                                                                      <CardContent>
                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-4 gap-3">
                                                                                                                                                                                                                                                                                                                                                                    {accentOptions.map(a => (
                                                                                                                                                                                                                                                                                                                                                                                      <button key={a.key} onClick={() => setAccent(a.key)}
                                                                                                                                                                                                                                                                                                                                                                                                          className={`p-3 rounded-xl border-2 flex flex-col items-center gap-2 transition-all ${
                                                                                                                                                                                                                                                                                                                                                                                                                                accent === a.key ? 'border-slate-900 dark:border-white' : 'border-transparent'
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="w-10 h-10 rounded-full" style={{ backgroundColor: a.color }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-xs text-slate-600 dark:text-slate-400">{a.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Card className="card-modern border-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <CardHeader><CardTitle className="text-slate-700 dark:text-slate-200 text-lg">Ukuran Kartu</CardTitle></CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-2 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {(['comfortable', 'compact'] as const).map(s => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button key={s} onClick={() => setCardSize(s)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={`p-4 rounded-xl border-2 transition-all text-sm font-medium ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cardSize === s ? 'accent-border accent-text' : 'border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {s === 'comfortable' ? 'Nyaman' : 'Ringkas'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }