'use client'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'

export default function Calculator() {
  const [display, setDisplay] = useState('0')
    const [prev, setPrev] = useState('')
      const [op, setOp] = useState('')

        const input = (val: string) => {
            if (display === '0' || display === 'Error') setDisplay(val)
                else setDisplay(display + val)
                  }

                    const calculate = () => {
                        try {
                              const result = eval(`${prev}${op}${display}`)
                                    setDisplay(String(result)); setPrev(''); setOp('')
                                        } catch { setDisplay('Error') }
                                          }

                                            const clear = () => { setDisplay('0'); setPrev(''); setOp('') }

                                              const buttons = ['7','8','9','/','4','5','6','*','1','2','3','-','0','.','=','+']

                                                return (
                                                    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-6">
                                                          <div className="max-w-xs mx-auto">
                                                                  <h1 className="text-3xl font-bold text-slate-800 dark:text-slate-100 mb-2">Kalkulator</h1>
                                                                          <p className="text-slate-500 mb-6">Operasi aritmatika dasar</p>
                                                                                  <Card className="card-modern border-0">
                                                                                            <CardContent className="pt-6 space-y-4">
                                                                                                        <div className="bg-slate-900 rounded-xl p-5 text-right text-3xl font-mono text-white min-h-[80px] overflow-hidden">
                                                                                                                      {display}
                                                                                                                                  </div>
                                                                                                                                              <div className="grid grid-cols-4 gap-2">
                                                                                                                                                            <Button variant="outline" onClick={clear} className="col-span-4 border-slate-300 text-slate-600">Clear</Button>
                                                                                                                                                                          {buttons.map(b => (
                                                                                                                                                                                          <Button key={b}
                                                                                                                                                                                                            variant={['=','+','-','*','/'].includes(b) ? 'default' : 'outline'}
                                                                                                                                                                                                                              className={
                                                                                                                                                                                                                                                  b === '=' ? 'accent-bg border-0'
                                                                                                                                                                                                                                                                      : ['+','-','*','/'].includes(b) ? 'bg-slate-700 hover:bg-slate-800 text-white border-0'
                                                                                                                                                                                                                                                                                          : 'border-slate-300 text-slate-700'
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                              onClick={() => {
                                                                                                                                                                                                                                                                                                                                                  if (b === '=') calculate()
                                                                                                                                                                                                                                                                                                                                                                      else if (['+','-','*','/'].includes(b)) {
                                                                                                                                                                                                                                                                                                                                                                                            if (prev && op) calculate()
                                                                                                                                                                                                                                                                                                                                                                                                                  setPrev(display); setOp(b); setDisplay('0')
                                                                                                                                                                                                                                                                                                                                                                                                                                      } else input(b)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {b}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }