'use client'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'

export default function Calculator() {
  const [display, setDisplay] = useState('0')
    const [prev, setPrev] = useState('')
      const [op, setOp] = useState('')

        const input = (val: string) => {
            if (display === '0' || display === 'Error') setDisplay(val)
                else setDisplay(display + val)
                  }

                    const calculate = () => {
                        try {
                              const result = eval(`${prev}${op}${display}`)
                                    setDisplay(String(result))
                                          setPrev('')
                                                setOp('')
                                                    } catch {
                                                          setDisplay('Error')
                                                              }
                                                                }

                                                                  const clear = () => {
                                                                      setDisplay('0')
                                                                          setPrev('')
                                                                              setOp('')
                                                                                }

                                                                                  const buttons = ['7','8','9','/','4','5','6','*','1','2','3','-','0','.','=','+']

                                                                                    return (
                                                                                        <div className="min-h-screen bg-gradient-to-br from-slate-100 to-blue-50 p-6">
                                                                                              <div className="max-w-xs mx-auto">
                                                                                                      <h1 className="text-2xl font-bold text-slate-800 mb-2">Kalkulator</h1>
                                                                                                              <p className="text-sm text-slate-500 mb-6">Operasi aritmatika dasar</p>
                                                                                                                      <Card className="bg-white border-slate-200 shadow-xl">
                                                                                                                                <CardContent className="pt-6 space-y-4">
                                                                                                                                            <div className="bg-slate-900 rounded-lg p-5 text-right text-3xl font-mono text-white min-h-[80px] overflow-hidden">
                                                                                                                                                          {display}
                                                                                                                                                                      </div>
                                                                                                                                                                                  <div className="grid grid-cols-4 gap-2">
                                                                                                                                                                                                <Button variant="outline" onClick={clear} className="col-span-4 border-slate-300 text-slate-600">
                                                                                                                                                                                                                Clear
                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                            {buttons.map((b) => (
                                                                                                                                                                                                                                                            <Button
                                                                                                                                                                                                                                                                              key={b}
                                                                                                                                                                                                                                                                                                variant={['=', '+', '-', '*', '/'].includes(b) ? 'default' : 'outline'}
                                                                                                                                                                                                                                                                                                                  className={
                                                                                                                                                                                                                                                                                                                                      b === '=' ? 'bg-blue-600 hover:bg-blue-700 text-white'
                                                                                                                                                                                                                                                                                                                                                          : ['+', '-', '*', '/'].includes(b) ? 'bg-slate-700 hover:bg-slate-800 text-white'
                                                                                                                                                                                                                                                                                                                                                                              : 'border-slate-300 text-slate-700'
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (b === '=') calculate()
                                                                                                                                                                                                                                                                                                                                                                                                                                                          else if (['+','-','*','/'].includes(b)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (prev && op) calculate()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setPrev(display)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setOp(b)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setDisplay('0')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else input(b)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {b}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }