'use client'
import { useState } from 'react'
import { Card, CardContent } from '@/components/ui/card'

const units: Record<string, Record<string, number>> = {
  Panjang: { Meter: 1, Kilometer: 1000, Centimeter: 0.01, Milimeter: 0.001, Inchi: 0.0254, Kaki: 0.3048, Mil: 1609.34, Yard: 0.9144 },
    Berat: { Kilogram: 1, Gram: 0.001, Miligram: 0.000001, Ton: 1000, Pound: 0.453592, Ounce: 0.0283495 },
      Volume: { Liter: 1, Mililiter: 0.001, 'Meter Kubik': 1000, Galon: 3.78541, Cup: 0.236588 },
        Data: { Byte: 1, KB: 1024, MB: 1048576, GB: 1073741824, TB: 1099511627776 },
        }

        export default function UnitConvert() {
          const [cat, setCat] = useState('Panjang')
            const [from, setFrom] = useState('Meter')
              const [to, setTo] = useState('Kilometer')
                const [val, setVal] = useState('1')

                  const result = (() => {
                      const n = parseFloat(val)
                          if (isNaN(n)) return ''
                              const base = n * units[cat][from]
                                  return (base / units[cat][to]).toFixed(6).replace(/\.?0+$/, '')
                                    })()

                                      const changeCat = (c: string) => {
                                          const keys = Object.keys(units[c])
                                              setCat(c); setFrom(keys[0]); setTo(keys[1])
                                                }

                                                  return (
                                                      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-6">
                                                            <div className="max-w-lg mx-auto">
                                                                    <h1 className="text-3xl font-bold text-slate-800 dark:text-slate-100 mb-2">Konverter Satuan</h1>
                                                                            <p className="text-slate-500 mb-6">Konversi berbagai satuan dengan mudah</p>
                                                                                    <Card className="card-modern border-0">
                                                                                              <CardContent className="pt-6 space-y-4">
                                                                                                          <div className="flex flex-wrap gap-2">
                                                                                                                        {Object.keys(units).map(c => (
                                                                                                                                        <button key={c} onClick={() => changeCat(c)}
                                                                                                                                                          className={`px-4 py-2 rounded-full text-xs font-medium ${cat === c ? 'accent-bg' : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>
                                                                                                                                                                            {c}
                                                                                                                                                                                            </button>
                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                <label className="text-sm text-slate-500">Nilai</label>
                                                                                                                                                                                                                                                              <input type="number" value={val} onChange={e => setVal(e.target.value)}
                                                                                                                                                                                                                                                                              className="w-full mt-1 px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100" />
                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-2 gap-3">
                                                                                                                                                                                                                                                                                                                    <select value={from} onChange={e => setFrom(e.target.value)}
                                                                                                                                                                                                                                                                                                                                    className="px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100">
                                                                                                                                                                                                                                                                                                                                                    {Object.keys(units[cat]).map(u => <option key={u}>{u}</option>)}
                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                <select value={to} onChange={e => setTo(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                className="px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100">
                                                                                                                                                                                                                                                                                                                                                                                                                {Object.keys(units[cat]).map(u => <option key={u}>{u}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="p-4 rounded-xl bg-slate-900 dark:bg-slate-800 text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-slate-400 mb-1">Hasil</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-2xl font-bold break-all">{result || '0'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }